knp_paginator:
    page_range: 5          # How many pages should be displayed on each side of the current page
    default_options:
        page_name: page    # Page query parameter name
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true     # Ensure distinct results, useful when ORM queries
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Use Twitter Bootstrap v4 pagination template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Sortable link template
